### PR TITLE
Idl_tree exchange format proposal.

### PR DESCRIPTION
**Pull request by marcosbracco**
I just created a sample idl_tree.h file under the lines I mentioned by mail.

I think is better to see and try, so please feel free to change as needed. If no big issues with this, let's merge to 'develop' branch.

Below is a dump of sample.idl, just to see how things would work:

[dump.txt](https://github.com/O-Log-N/Hare-IDL/files/148805/dump.txt)
[sample.idl.txt](https://github.com/O-Log-N/Hare-IDL/files/148808/sample.idl.txt)

### CODE REVIEW

**Comment by nobugs-hare** [comment]
It is a good starting point, thanks a lot. There are, however, some things we'll need to fix/change:
- As I understand the logic, DataType::KIND should describe which fields are used (effectively being a selector of "discriminated union"), shouldn't it? Then SEQUENCE and VECTOR are the same KIND (I suggest SEQUENCE), with different 'name'
- To handle SEQUENCE, (as there can be `SEQUENCE<Item>` as well as `SEQUENCE<int>`) in any case we need to add `DataType::unique_ptr<DataType> paramType;` In addition, to simplify code on the 'back' side, _I suggest to say that in DataType::paramType CANNOT be KIND::SEQUENCE (i.e. that it is a job of 'front' to introduce a typedef which handles it)_
- to do it (and for many other reasons) we'll need to introduce `vector<Typedef>` into Root, with Typedef being like { string name; DataType type; }; appropriate syntax should be added to IDL too
- then KIND::CLASS effectively becomes KIND::NAMED_TYPE (and can point to struct or to typedef, front cannot distinguish between the two without name resolution which it shouldn't do)
- I suggest to rename PLAIN into PRIMITIVE ('PLAIN' has associations with 'POD' which is not what is meant)
- under the same logic of KIND being field selector, PLAIN/PRIMITIVE and NUMERIC are different KINDs, so I suggest to introduce KIND of LIMITED_PRIMITIVE or PRIMITIVE_WITH_LIMITS (see below)
- DataType::arguments as `vector<float>`? At least for NUMERIC, I prefer to use KIND::LIMITED_PRIMITIVE with fields Limit lowLimit; Limit highLimit; with Limit being a struct of {bool inclusive;double value;}).
- Overall, I suggest to use double instead of float (why not?)
- I suggest to introduce type Variant (which can contain any primitive type, or string, or whatever-else we need). EncodedMember::defaultValue should be of Variant type (at the very least it can be a string).
- EncodedMember::defaulValue contains a typo
- instead of EncodedMembers::tags and instead of EncodingAttributes::arguments I suggest to introduce name-value pairs, with name being string, and value being Variant. It will need changes to IDL too, for example, MAPPING(Lang="CPP",Role="Server") - and DEAD_RECKONING(Tolerance=0.02)
- there is a typo in FIXED_PONIT 
- As we're C++11, I suggest to use int lineNumber = 0; instead of constructors (it's more obvious etc.). Will add another item to STYLE-GUIDE about it

Phew, further comments and criticism are VERY welcome

**Comment by marcosbracco** [comment]
I have pushed most of this changes, and rebased code onto 'develop' branch
Still missing typedef part, and changes to grammar to support MAPPING(Lang="CPP",Role="Server")

Also added DataType::KIND: FIXED_POINT and BIT,
to enable fields: DataType::fixedPointPresicion and DataType::bitSize

Comments are welcome

**Comment by marcosbracco** [comment]
Also missing the change from KIND::CLASS to KIND::NAMED_TYPE,
Currently KIND::CLASS is associated with the 'class' keyword syntax:

`
MAPPING(Lang="CPP",Role="Server") PUBLISHABLE_STRUCT Character {
  class MyInventory inventory;
`
Should we drop the 'class' keyword, and use NAMED_TYPE for any type name not being a keyword? or should be class keyword always required to reference a generic NAMED_TYPE?

**Comment by nobugs-hare** [comment]
I'm starting to like it :-). 

A few further comments:
- we don't want to have encoding-specific stuff (such as FIXED_POINT and BIT) in the KIND space; doing it would mean changing the grammar for each of encodings, which we want to avoid. So, I suggest (a) to change IDL syntax to FIXED_POINT(precision=0.01) and BIT(length=2), (b) to drop KIND=FIXED_POINT and BIT (and associated fields), (c) to make new KIND=ENCODING_SPECIFIC, with a respective field of `vector<pair<string,Variant> > encodingAttributes;`, (d) to use this ENCODING_SPECIFIC to represent FIXED_POINT and BIT.
- EncodedMembers::tags should also be replaced with `vector<pair<string,Variant> > encodingAttributes;` (and respective syntax should be changed too)
- I suggest to rename EncodingAttributes::arguments to encodingAttributes.
- a question about 'class' in MAPPING is a separate and non-trivial one, I will comment on it later

**Comment by nobugs-hare** [comment]
About 'class XXX' in mappings.

Mappings (unlike IDL itself and ENCODING) are very special beasts. In particular, _in the near future we'll need to parse target language code (like "C++ code from .h/.cpp file) to get mappings right from there_. 

As a result, I suggest to _use the same target-language syntax within MAPPING clause of IDL_, to make it more consistent and straightforward for developer-using-IDL.

In other words, parser will need to parse until MAPPING, and then to invoke C++ parser (or JavaScript parser, or...) to parse MAPPING itself. To simplify parsing, I suggest to say that MAPPING belongs to a separate file (with a clause in main IDL file like MAPPING_FILE(CPP,file_name)). 

Then, syntax of MAPPINGs becomes target-language-specific. However, we do need to fit it into our DataType. To do it, I suggest to introduce new KIND=MAPPING_SPECIFIC, and to use yet another `vector<pair<string,Variant> > mappingAttributes;` to encode it.  How to encode specific `class XXX` into name/mappingAttributes, is not that important (one example may use name='class', and have mappingAttributes as `{{"className","XXX"}}`).

**Comment by marcosbracco** [comment]
I pushed new iteration for review.
I think all of the comments above have been taken care of (with exception of Typedef, still to be defined)

`Structure` now has `vector<pair<string, Variant> > encodingAttributes;`, but is also inheriting from `EncodedMembers` a `EncodingAttributes encodingAttr;`
This is a confusing because names are too similar.

**Comment by nobugs-hare** [comment]
Do we really need Structure::encodingAttributes; (non-inherited one)? At the first glance, it doesn't look so...

**Comment by nobugs-hare** [comment]
A bunch of suggested renamings to streamline things (I hope that more or less final ones now):
- rename class EncodingAttributes -> EncodingSpecifics ('attributes' usually understood as 'name-value pairs', and this class is more than that)
- rename EncodedMembers::encodingAttr -> encodingSpecifics
- rename EncodingSpecifics::encodingAttributes -> attrs
- rename DataType::encodingAttributes -> encodingAttrs
- rename DataType::mappingAttributes -> mappingAttrs

Also, I'd suggest to change types of DataType::encodingAttrs, DataType::mappingAttrs, and EncodedSpecific::attrs to map<string,Variant> (it simplifies handling, and emphasizes that order is immaterial); by the same logic, suggest to change DataType::enumValues into map<string,int> _(and it should be responsibility of the front-end to fill in all the missing values in accordance with rules of the source language if any)_.

After this is done, I am going to close this pull request (as a version is already included into develop, merging it is not an option), and if there are any further changes needed - we'll go via new issues.

**Pull request closed without merging**
